import tkinter as tk
from tkinter import ttk

class Aplicacion():
    def __init__(self):
        self.ventana1=tk.Tk()
        self.ventana1.title("Password manager")
        self.ventana1.geometry("300x300")
        self.cuaderno1 = ttk.Notebook(self.ventana1)

        self.pagina1 = ttk.Frame(self.cuaderno1)
        self.cuaderno1.add(self.pagina1,text="Iniciar Sesión")
        self.label1=ttk.Label(self.pagina1,text="Usuario:")
        self.label1.grid(column=0,row=0)
        self.usuario=tk.StringVar()
        self.entrada_usuario=ttk.Entry(self.pagina1,width=25,textvariable=self.usuario)
        self.entrada_usuario.grid(column=1,row=0)
        self.label2=ttk.Label(self.pagina1,text="Contraseña:")
        self.label2.grid(column=0,row=1)
        self.passwd=tk.StringVar()
        self.entrada_passwd=ttk.Entry(self.pagina1,width=25,textvariable=self.passwd)
        self.entrada_passwd.grid(column=1,row=1)
        self.boton1=ttk.Button(self.pagina1, text="Cancelar")
        self.boton1.grid(column=0,row=2)
        self.boton2=ttk.Button(self.pagina1, text="Aceptar")
        self.boton2.grid(column=1,row=2)

        self.pagina2 = ttk.Frame(self.cuaderno1)
        self.cuaderno1.add(self.pagina2,text="Añadir Usuario")
        self.label1=ttk.Label(self.pagina2,text="Usuario:")
        self.label1.grid(column=0,row=0)
        self.usuario=tk.StringVar()
        self.entrada_usuario=ttk.Entry(self.pagina2,width=25,textvariable=self.usuario)
        self.entrada_usuario.grid(column=1,row=0)
        self.label2=ttk.Label(self.pagina2,text="Contraseña:")
        self.label2.grid(column=0,row=1)
        self.passwd=tk.StringVar()
        self.entrada_passwd=ttk.Entry(self.pagina2,width=25,textvariable=self.passwd)
        self.entrada_passwd.grid(column=1,row=1)
        self.label3=ttk.Label(self.pagina2,text="Confirmar Contraseña:")
        self.label3.grid(column=0,row=2)
        self.confirma_passwd=tk.StringVar()
        self.confirma_passwd=ttk.Entry(self.pagina2,width=25,textvariable=self.passwd)
        self.confirma_passwd.grid(column=1,row=2)
        self.boton1=ttk.Button(self.pagina2, text="Cancelar")
        self.boton1.grid(column=0,row=3)
        self.boton2=ttk.Button(self.pagina2, text="Aceptar")
        self.boton2.grid(column=1,row=3)

        self.cuaderno1.grid(column=0, row=0)
        self.ventana1.mainloop()
app1=Aplicacion()